### ISSUE TITLE
Crashes on load

### ISSUE THREAD

**Issue by SalamanderSandwich** [m35/jpsxdec#12]
Environment
-------------

jPSXdec version: 0.99.8
Operating system: Windows 10
Java runtime environment: Java 10.0.1

 Description 
-------------

What happened?: Crashes on opening

Not sure where the log is, but running it in cmd gives me this
```
Exception in thread "AWT-EventQueue-0" java.lang.ExceptionInInitializerError
        at org.jdesktop.swingx.JXTable.<clinit>(JXTable.java:379)
        at jpsxdec.gui.Gui.initComponents(Gui.java:459)
        at jpsxdec.gui.Gui.<init>(Gui.java:114)
        at jpsxdec.Main$1.run(Main.java:125)
        at java.desktop/java.awt.event.InvocationEvent.dispatch(Unknown Source)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.desktop/java.awt.EventQueue.access$600(Unknown Source)
        at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
        at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)
Caused by: java.lang.IllegalArgumentException: org.jdesktop.swingx.plaf.LookAndFeelAddons is not an ImageIO SPI class
        at java.desktop/javax.imageio.spi.ServiceRegistry.checkClassAllowed(Unknown Source)
        at java.desktop/javax.imageio.spi.ServiceRegistry.lookupProviders(Unknown Source)
        at org.jdesktop.swingx.plaf.LookAndFeelAddons.getSystemAddonClassName(LookAndFeelAddons.java:300)
        at org.jdesktop.swingx.plaf.LookAndFeelAddons.getBestMatchAddonClassName(LookAndFeelAddons.java:259)
        at org.jdesktop.swingx.plaf.LookAndFeelAddons.<clinit>(LookAndFeelAddons.java:87)
        ... 18 more
```

**Comment by SalamanderSandwich** [comment]
Ran java update like i should've done before the post, works now. Sorry.
