### ISSUE TITLE
Doesn't start on Linux

### ISSUE THREAD

**Issue by AJenbo** [m35/jpsxdec#17]
Environment
-------------

jPSXdec version: v0.99.8
Operating system: Ubuntu 18.10 64bit
Java runtime environment: openjdk version "1.8.0_191"
OpenJDK Runtime Environment (build 1.8.0_191-8u191-b12-2ubuntu0.18.10.1-b12)
OpenJDK 64-Bit Server VM (build 25.191-b12, mixed mode)

PlayStation Game: 
----------------------------------
Name: Diablo

Description 
-------------

What happened?:
Exception in thread "main" java.awt.AWTError: Assistive Technology not found: org.GNOME.Accessibility.AtkWrapper
	at java.awt.Toolkit.loadAssistiveTechnologies(Toolkit.java:807)
	at java.awt.Toolkit.getDefaultToolkit(Toolkit.java:886)
	at java.awt.Toolkit.getEventQueue(Toolkit.java:1736)
	at java.awt.EventQueue.invokeLater(EventQueue.java:1294)
	at jpsxdec.Main.main(Main.java:123)

What was supposed to happen?: The application UI appears on screen

What were you doing?: java -jar jpsxdec.jar

**Comment by AJenbo** [comment]
My bad was using headless java
